source/accounts/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from source.accounts.views import MyRegisterView

app_name = 'accounts'

urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('registration/', MyRegisterView.as_view(), name='registration'),
]

source/hello/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('webapp.urls')),
    path('account/', include('accounts.urls')),
]

source/webapp/urls.py
from django.urls import path

from .views import TaskView, TaskCreate, TaskDelete, TaskUpdate, TaskDetail


app_name = 'webapp'

urlpatterns = [

    path('', TaskView.as_view(), name='index'),
    path('detail/<int:pk>/', TaskDetail.as_view(), name='task_detail'),
    path('create/', TaskCreate.as_view(), name='task_create'),
    path('<int:pk>/delete/', TaskDelete.as_view(), name='task_delete'),
    path('<int:pk>/update/', TaskUpdate.as_view(), name='task_update'),

]

source/accounts/models.py
from django.db import models

# Create your models here.

source/webapp/models.py
from django.db import models


class BaseModel(models.Model):
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Время создания')
    updated_at = models.DateTimeField(auto_now=True, verbose_name='Время обновления')

    class Meta:
        abstract = True


class TaskModel(BaseModel):
    task_name = models.CharField(max_length=50, verbose_name='Название')
    description = models.TextField(max_length=1000, null=True, blank=True, verbose_name='Описание')
    status = models.ForeignKey('TaskStatus', on_delete=models.CASCADE, related_name='statuses', verbose_name='Статус')
    type = models.ManyToManyField('TaskType', related_name='types', verbose_name='Тип')

    def __str__(self):
        return f'{self.task_name}, {self.description}'

    class Meta:
        db_table = 'TaskModel'
        verbose_name = 'Задача'
        verbose_name_plural = 'Задачи'


class TaskType(models.Model):
    type_name = models.CharField(max_length=20, verbose_name='Имя типа')

    def __str__(self):
        return f'{self.type_name}'

    class Meta:
        db_table = 'TaskType'
        verbose_name = 'Тип'
        verbose_name_plural = 'Типы'


class TaskStatus(models.Model):
    status_name = models.CharField(max_length=20, verbose_name='Имя статуса')

    def __str__(self):
        return f'{self.status_name}'

    class Meta:
        db_table = 'TaskStatus'
        verbose_name = 'Статус'
        verbose_name_plural = 'Статусы'

source/accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm


class MyUserCreationForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta(UserCreationForm.Meta):
        fields = ['username', 'password1', 'password2', 'first_name', 'last_name', 'email']

source/webapp/forms.py
from django import forms

from .models import TaskModel


class TaskCreateForm(forms.ModelForm):
    class Meta:
        model = TaskModel
        fields = ['task_name', 'description', 'status', 'type']
        widgets = {
            'status': forms.RadioSelect,
            'type': forms.CheckboxSelectMultiple
        }

source/accounts/views.py
from django.contrib.auth import login
from django.contrib.auth.models import User
from django.shortcuts import redirect
from django.urls import reverse
from django.views.generic import CreateView

from source.accounts.forms import MyUserCreationForm


class MyRegisterView(CreateView):
    model = User
    template_name = 'registration/register.html'
    form_class = MyUserCreationForm

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return redirect(self.get_success_url())

    def get_success_url(self):
        next_url = self.request.GET.get('next')
        if not next_url:
            next_url = self.request.GET.get('next')
        if not next_url:
            next_url = reverse('webapp:index')
        return next_url

source/webapp/views.py
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.shortcuts import redirect
from django.urls import reverse, reverse_lazy
from django.views.generic import ListView, CreateView, DeleteView, UpdateView, DetailView

from .forms import TaskCreateForm
from .models import TaskModel


class TaskView(ListView):
    model = TaskModel
    template_name = 'index.html'
    context_object_name = 'tasks'


class TaskDetail(DetailView):
    model = TaskModel
    template_name = 'task_detail.html'
    context_object_name = 'task'


class TaskCreate(PermissionRequiredMixin, CreateView):
    form_class = TaskCreateForm
    template_name = 'task_create.html'
    permission_required = 'webapp:add'

    def get_success_url(self):
        return reverse('webapp:index')


class TaskDelete(DeleteView):
    model = TaskModel
    template_name = 'task_delete.html'
    success_url = reverse_lazy('index')
    context_object_name = 'task'


class TaskUpdate(PermissionRequiredMixin, UpdateView):
    model = TaskModel
    form_class = TaskCreateForm
    template_name = 'task_update.html'
    permission_required = 'webapp:change'

    def get_success_url(self):
        return reverse('webapp:index')

source/webapp/templates/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
<div class="container">
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'webapp:index' %}">Задачи</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        {% block nav %} {% endblock %}
{#        <li class="nav-item">#}
{#          <a class="nav-link" href="#">Link</a>#}
{#        </li>#}
{#        <li class="nav-item dropdown">#}
{#          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown"#}
{#             aria-expanded="false">#}
{#            Dropdown#}
{#          </a>#}
{#          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">#}
{#            <li><a class="dropdown-item" href="#">Action</a></li>#}
{#            <li><a class="dropdown-item" href="#">Another action</a></li>#}
{#            <li><hr class="dropdown-divider"></li>#}
{#            <li><a class="dropdown-item" href="#">Something else here</a></li>#}
{#          </ul>#}
{#        </li>#}
{#        <li class="nav-item">#}
{#          <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>#}
{#        </li>#}
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav><br>
    {% block content %}{% endblock %}
</div>
</body>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>
</html>

source/webapp/templates/index.html
{% extends 'base.html' %}

{% block title %}Список{% endblock %}
{% block nav %}
    {% if not user.is_authenticated %}
       <li class="nav-item">
        <a class="nav-link active" aria-current="page" href="{% url 'accounts:registration' %}">Регистрация</a>
    </li>
    {% endif %}
    {% if user.is_authenticated %}
        <li class="nav-item">
        <a class="nav-link active" aria-current="page" href="{% url 'webapp:task_create' %}">Добавить</a>
    </li>
    <li class="nav-item">
        <a class="nav-link active" aria-current="page" href="{% url 'accounts:logout' %}">Выйти</a>
    </li>
    {% else %}
    <li class="nav-item">
        <a class="nav-link active" aria-current="page" href="{% url 'accounts:login' %}">Войти</a>
    </li>
    {% endif %}
{% endblock %}
{% block content %}
    <p>{{ request.user }}</p>
    {% for task in tasks %}
        <div class="card mb-3" style="max-width: 540px;">
          <div class="row g-0">
            <div class="col-md-4">
              <img src="..." class="img-fluid rounded-start" alt="...">
            </div>
            <div class="col-md-8">
              <div class="card-body">
                  <a href="{% url 'webapp:task_detail' task.pk %}" style="text-decoration: none"><h4>{{ task.task_name }}</h4></a>
                <h5>{{ task.description }}</h5>
                <p style="font-weight: bold">{{ task.status }}</p>
                  {% for type in task.type.all %}
                      <p style="font-weight: bold; color: #7dc07d">{{ type }}</p>
                  {% endfor %}
                  <p class="card-text"><small class="text-muted">{{ task.created_at }}</small></p>
              </div>
            </div>
          </div>
</div>
    {% endfor %}
{% endblock %}

source/webapp/templates/partial/form.html
{% csrf_token %}


{% for field in form %}
   <p><label for="{{ field.id_for_label }}">{{ field.label }}</label>{{ field.category }}</p>
   {% for error in field.errors %}
       <p class="text-danger">{{ error }}</p>
   {% endfor %}
   <p>{{ field }}</p>
{% endfor %}

<input type="submit" value="{{ button_text }}"/>

source/webapp/templates/task_create.html
{% extends 'base.html' %}

{% block title %}Добавление{% endblock %}

{% block content %}
        <h3>Новая задача</h3>
    <form action="" method="post">
        {% include "partial/form.html" with button_text="Добавить" %}
    </form>
{% endblock %}

source/webapp/templates/task_delete.html
{% extends 'base.html' %}

{% block title %}Удаление{% endblock %}

{% block content %}
    <h5>Вы уверены, что хотите удалить задачу "{{ task.description }}"?</h5>
    <form action="{% url 'webapp:task_delete' task.pk %}" method="post">
        {% csrf_token %}
        <div class="btn-group">
            <button class="btn btn-warning" type="submit">Да</button>
            <a class="btn btn-primary" href="{% url 'webapp:index' %}">Нет</a>
        </div>
    </form>
{% endblock %}

source/webapp/templates/task_detail.html
{% extends 'base.html' %}

{% block title %}Детально{% endblock %}

{% block nav %}
    {% if user.is_authenticated %}
        <li class="nav-item">
        <a class="nav-link active" aria-current="page" href="{% url 'webapp:task_delete' task.pk %}">Удалить</a>
    </li>
        <li class="nav-item">
        <a class="nav-link active" aria-current="page" href="{% url 'webapp:task_update' task.pk %}">Изменить</a>
    </li>
    {% endif %}
{% endblock %}

{% block content %}
    <div class="card mb-3" style="max-width: 540px;">
  <div class="row g-0">
    <div class="col-md-4">
      <img src="..." class="img-fluid rounded-start" alt="...">
    </div>
    <div class="col-md-8">
      <div class="card-body">
          <h4>{{ task.task_name }}</h4>
        <h5>{{ task.description }}</h5>
        <p style="font-weight: bold">{{ task.status }}</p>
          {% for type in task.type.all %}
              <p style="font-weight: bold; color: #7dc07d">{{ type }}</p>
          {% endfor %}
          <p class="card-text"><small class="text-muted">{{ task.created_at }}</small></p>
      </div>
    </div>
  </div>
</div>
{% endblock %}

source/webapp/templates/task_update.html
{% extends 'base.html' %}

{% block title %}Изменение{% endblock %}

{% block content %}
        <h3>Изменение задачи</h3>
    <form action="" method="post">
        {% include "partial/form.html" with button_text="Изменить" %}
    </form>
{% endblock %}